# Setup
title:        Salveamicus
tagline:      A developer currently working on several projects, not limited to the pyscope python library and some as yet unpublished C++ mathematics libraries. 
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       James Osborne
  url:        https://www.linkedin.com/in/james-osborne-6b2112261/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
